// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEVrMKxr_QMOD9X_eBRfPCqAtgeM6efx8',
    appId: '1:304904194906:web:bf3d32450a23f503348163',
    messagingSenderId: '304904194906',
    projectId: 'todo-app-bea68',
    authDomain: 'todo-app-bea68.firebaseapp.com',
    storageBucket: 'todo-app-bea68.appspot.com',
    measurementId: 'G-6ZQ9WXTZT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_PgvqOE0G7hUMqjMoqccgv-7w6zCd3YM',
    appId: '1:304904194906:android:7a1a26885fb13863348163',
    messagingSenderId: '304904194906',
    projectId: 'todo-app-bea68',
    storageBucket: 'todo-app-bea68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW0ye3B3sfrzlbTV5Jt4sfI0JURxswBHM',
    appId: '1:304904194906:ios:67a7e1515936f990348163',
    messagingSenderId: '304904194906',
    projectId: 'todo-app-bea68',
    storageBucket: 'todo-app-bea68.appspot.com',
    iosClientId: '304904194906-erpjn5gc4sev8mjs9n7qoljpfvrvjjfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW0ye3B3sfrzlbTV5Jt4sfI0JURxswBHM',
    appId: '1:304904194906:ios:67a7e1515936f990348163',
    messagingSenderId: '304904194906',
    projectId: 'todo-app-bea68',
    storageBucket: 'todo-app-bea68.appspot.com',
    iosClientId: '304904194906-erpjn5gc4sev8mjs9n7qoljpfvrvjjfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
